#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

language: generic

os:
  - linux

services:
  - docker

git:
  submodules: false

jobs:
  include:
  - stage: Debian Container
    script:
      - git submodule update --init --remote
      - |
        tools/build/build_container.sh \
        --envfile versions/debian-10.env \
        --envfile versions/docker-picard.env \
        --build \
        --pushdr

  - stage: Docker Testing
    script: 
      - git submodule update --init --remote
      - |
        tools/build/build_container.sh \
        --envfile versions/docker-picard.env \
        --testc

  - stage: Git Tag & Docker Hub README
    script: 
      - git submodule update --init --remote
      - |
        tools/build/build_container.sh \
        --envfile versions/docker-picard.env \
        --pushgt \
        --pushrm
