#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

language: generic

os:
  - linux

services:
  - docker

git:
  submodules: false

jobs:
  include:
  - stage: Debian Container
    script:
      - git submodule update --init --recursive
      - source tools/scripts/load_env_files.sh versions/debian-10.env versions/docker-picard.env
      - source tools/scripts/versioning.sh 
      - tools/scripts/make_container.sh
    deploy:
        provider: script
        script: tools/scripts/push_to_registry.sh

  - stage: Git Tag & Docker Hub README
    script: 
      - git submodule update --init --recursive
      - source tools/scripts/load_env_files.sh versions/docker-picard.env
      - source tools/scripts/versioning.sh
      - tools/scripts/push_git_tag.sh
      - tools/scripts/push_readme_to_dockerhub.sh